name: TEST Predict Action

on: [workflow_dispatch]

jobs:
  predict-cost:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./

      - name: Test single workload file
        id: single-workload
        uses: ./
        with:
          log_level: "info"
          path: ./test/workload.yaml

      - name: Output single workload prediction
        run: |
          echo "${{ steps.single-workload.outputs.PREDICTION_TABLE }}"

      - name: Test directory with multiple workloads
        id: multi-workload
        uses: ./
        with:
          log_level: "info"
          path: ./test/subdir

      - name: Output multi workload prediction
        run: |
          echo "${{ steps.multi-workload.outputs.PREDICTION_TABLE }}"

      - name: Test workload with unsupported resources
        id: unsupported-resources
        uses: ./
        with:
          log_level: "warn"
          path: ./test/subdir/multi-with-unsupported.yaml

      - name: Output unsupported resources prediction
        run: |
          echo "${{ steps.unsupported-resources.outputs.PREDICTION_TABLE }}"
